name: Generate Docker image and Trigger Jenkins

on:
  push:
    branches:
      - master  # 트리거할 브랜치

jobs:
  build-and-trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 1️⃣ Docker Hub 로그인
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 2️⃣ Docker 이미지 빌드
      - name: Build Docker Image
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/thinkfast-backend
          VERSION=$(date +%Y%m%d%H%M)
          echo "Building image: $IMAGE_NAME:$VERSION"
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:$VERSION .
